name: CI

on: [push]

jobs:
  "linter-and-tests":

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: yarn
    - name: Run linter
      run: yarn lint
    - name: Run tests
      run: yarn test

